name: feature-env
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.6.3
  - numpy
  - matplotlib
  - pandas
  - shapely
  - pymongo
  - openslide
  - scikit-image
  - opencv
  - pip:
    - git+https://github.com/jrosebr1/imutils.git
